name: my_uz
description: Aplikacja mobilna dla studentów Uniwersytetu Zielonogórskiego
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  table_calendar: ^3.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/illustrations/
    - assets/logo.png
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: lib/fonts/Inter-Thin.otf
          weight: 100
        - asset: lib/fonts/Inter-Light.otf
          weight: 300
        - asset: lib/fonts/Inter-Regular.otf
          weight: 400
        - asset: lib/fonts/Inter-Medium.otf
          weight: 500
        - asset: lib/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: lib/fonts/Inter-Bold.otf
          weight: 700
        - asset: lib/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: lib/fonts/Inter-Black.otf
          weight: 900
    - family: MyUz
      fonts:
        - asset: lib/fonts/MyUz.ttf

# Konfiguracja generatora ikon aplikacji (flutter_launcher_icons)
# Używa pliku: assets/logo.png (wybierz PNG 1024x1024 dla najlepszej jakości)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#68548E"
