package com.example.my_uz_android.ui.theme

import androidx.compose.ui.graphics.Color

// --- Podstawowe (bez zmian) ---
val md_theme_light_primary = Color(0xFF68548e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFebddff)
val md_theme_light_onPrimaryContainer = Color(0xFF4f3d74)
val md_theme_light_secondary = Color(0xFF635b70)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe9def8)
val md_theme_light_onSecondaryContainer = Color(0xFF4b4358)
val md_theme_light_tertiary = Color(0xFF7e525d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9e1)
val md_theme_light_onTertiaryContainer = Color(0xFF643b46)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFfef7ff)
val md_theme_light_onBackground = Color(0xFF1d1b20)
val md_theme_light_surface = Color(0xFFfef7ff)
val md_theme_light_onSurface = Color(0xFF1d1b20)
val md_theme_light_surfaceVariant = Color(0xFFe7e0eb)
val md_theme_light_onSurfaceVariant = Color(0xFF49454e)
val md_theme_light_outline = Color(0xFF7a757f)
val md_theme_light_outlineVariant = Color(0xFFcbc4cf)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF322f35)
val md_theme_light_inverseOnSurface = Color(0xFFf5eff7)
val md_theme_light_inversePrimary = Color(0xFFd3bcfd)

// --- LIGHT: Rozszerzone ---
val md_theme_light_surfaceDim = Color(0xFFded8e0)
val md_theme_light_surfaceBright = Color(0xFFfef7ff)
val md_theme_light_surfaceContainerLowest = Color(0xFFffffff)
val md_theme_light_surfaceContainerLow = Color(0xFFf8f1fa)
val md_theme_light_surfaceContainer = Color(0xFFf2ecf4)
val md_theme_light_surfaceContainerHigh = Color(0xFFede6ee)
val md_theme_light_surfaceContainerHighest = Color(0xFFe7e0e8)
val md_theme_light_primaryFixed = Color(0xFFebddff)
val md_theme_light_onPrimaryFixed = Color(0xFF230f46)
val md_theme_light_primaryFixedDim = Color(0xFFd3bcfd)
val md_theme_light_onPrimaryFixedVariant = Color(0xFF4f3d74)
val md_theme_light_secondaryFixed = Color(0xFFe9def8)
val md_theme_light_onSecondaryFixed = Color(0xFF1f182b)
val md_theme_light_secondaryFixedDim = Color(0xFFcdc2db)
val md_theme_light_onSecondaryFixedVariant = Color(0xFF4b4358)
val md_theme_light_tertiaryFixed = Color(0xFFffd9e1)
val md_theme_light_onTertiaryFixed = Color(0xFF31101b)
val md_theme_light_tertiaryFixedDim = Color(0xFFf0b7c5)
val md_theme_light_onTertiaryFixedVariant = Color(0xFF643b46)

// --- DARK: Podstawowe ---
val md_theme_dark_primary = Color(0xFFd3bcfd)
val md_theme_dark_onPrimary = Color(0xFF38265c)
val md_theme_dark_primaryContainer = Color(0xFF4f3d74)
val md_theme_dark_onPrimaryContainer = Color(0xFFebddff)
val md_theme_dark_secondary = Color(0xFFcdc2db)
val md_theme_dark_onSecondary = Color(0xFF342d40)
val md_theme_dark_secondaryContainer = Color(0xFF4b4358)
val md_theme_dark_onSecondaryContainer = Color(0xFFe9def8)
val md_theme_dark_tertiary = Color(0xFFf0b7c5)
val md_theme_dark_onTertiary = Color(0xFF4a2530)
val md_theme_dark_tertiaryContainer = Color(0xFF643b46)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9e1)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF151218)
val md_theme_dark_onBackground = Color(0xFFe7e0e8)
val md_theme_dark_surface = Color(0xFF151218)
val md_theme_dark_onSurface = Color(0xFFe7e0e8)
val md_theme_dark_surfaceVariant = Color(0xFF49454e)
val md_theme_dark_onSurfaceVariant = Color(0xFFcbc4cf)
val md_theme_dark_outline = Color(0xFF948f99)
val md_theme_dark_outlineVariant = Color(0xFF49454e)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFe7e0e8)
val md_theme_dark_inverseOnSurface = Color(0xFF322f35)
val md_theme_dark_inversePrimary = Color(0xFF68548e)

// --- DARK: Rozszerzone ---
val md_theme_dark_surfaceDim = Color(0xFF151218)
val md_theme_dark_surfaceBright = Color(0xFF3b383e)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0f0d13)
val md_theme_dark_surfaceContainerLow = Color(0xFF1d1b20)
val md_theme_dark_surfaceContainer = Color(0xFF211f24)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2c292f)
val md_theme_dark_surfaceContainerHighest = Color(0xFF36343a)
val md_theme_dark_primaryFixed = Color(0xFFebddff)
val md_theme_dark_onPrimaryFixed = Color(0xFF230f46)
val md_theme_dark_primaryFixedDim = Color(0xFFd3bcfd)
val md_theme_dark_onPrimaryFixedVariant = Color(0xFF4f3d74)
val md_theme_dark_secondaryFixed = Color(0xFFe9def8)
val md_theme_dark_onSecondaryFixed = Color(0xFF1f182b)
val md_theme_dark_secondaryFixedDim = Color(0xFFcdc2db)
val md_theme_dark_onSecondaryFixedVariant = Color(0xFF4b4358)
val md_theme_dark_tertiaryFixed = Color(0xFFffd9e1)
val md_theme_dark_onTertiaryFixed = Color(0xFF31101b)
val md_theme_dark_tertiaryFixedDim = Color(0xFFf0b7c5)
val md_theme_dark_onTertiaryFixedVariant = Color(0xFF643b46)

// --- NOWE KOLORY KART ---
val card_class_light = Color(0xFFE8DEF8)
val card_class_dark = Color(0xFF4B4358)

val card_event_light = Color(0xFFDAF5D7)
val card_event_dark = Color(0xFF2D4F31)

// Custom colors
val custom_red_light = Color(0xFF904a43)
val custom_green_light = Color(0xFF3c6839)
val custom_orange_light = Color(0xFF8e4d32)
val custom_blue_light = Color(0xFF38608f)

val custom_red_dark = Color(0xFFffb4ab)
val custom_green_dark = Color(0xFFa2d399)
val custom_orange_dark = Color(0xFFffb599)
val custom_blue_dark = Color(0xFFa2c9fe)

// Home Screen Colors
val home_header_light = Color(0xFFF7F2F9)
val home_header_dark = Color(0xFF141218)
val home_content_light = Color(0xFFFFFFFF)
val home_content_dark = Color(0xFF1D1B20)

// ✅ Top section - F7F2F9!
val home_top_background_light = Color(0xFFF7F2F9)
val home_top_background_dark = Color(0xFF1D1B20)

// Navigation
val nav_light_background = Color(0xFFFFFFFF)
val nav_light_border = Color(0xFFEDE6F3)
val nav_light_active = Color(0xFF381E72)
val nav_light_inactive = Color(0xFF787579)

val nav_dark_background = Color(0xFF1D1B20)
val nav_dark_border = Color(0xFF49454e)
val nav_dark_active = Color(0xFFd3bcfd)
val nav_dark_inactive = Color(0xFFcac4d0)

val button_background_light = Color(0xFFE8DEF8)
val button_background_dark = Color(0xFF4B4358)

val icon_text_light = Color(0xFF000000)
val icon_text_dark = Color(0xFFE7E0E8)