package com.example.my_uz_android.ui.theme

import androidx.compose.ui.graphics.Color

// --- Dodane brakujące kolory ---
val Pink40 = Color(0xFF7D5260)
val Purple40 = Color(0xFF6650a4)

// --- Light Theme Colors ---
val md_theme_light_primary = Color(0xFF68548e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFebddff)
val md_theme_light_onPrimaryContainer = Color(0xFF4f3d74)
val md_theme_light_secondary = Color(0xFF635b70)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe9def8)
val md_theme_light_onSecondaryContainer = Color(0xFF4b4358)
val md_theme_light_tertiary = Color(0xFF7e525d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9e1)
val md_theme_light_onTertiaryContainer = Color(0xFF643b46)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFfef7ff)
val md_theme_light_onBackground = Color(0xFF1d1b20)
val md_theme_light_surface = Color(0xFFfef7ff)
val md_theme_light_onSurface = Color(0xFF1d1b20)
val md_theme_light_surfaceVariant = Color(0xFFe7e0eb)
val md_theme_light_onSurfaceVariant = Color(0xFF49454e)
val md_theme_light_outline = Color(0xFF7a757f)
val md_theme_light_outlineVariant = Color(0xFFcbc4cf)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF322f35)
val md_theme_light_inverseOnSurface = Color(0xFFf5eff7)
val md_theme_light_inversePrimary = Color(0xFFd3bcfd)

// --- Dark Theme Colors ---
val md_theme_dark_primary = Color(0xFFd3bcfd)
val md_theme_dark_onPrimary = Color(0xFF38265c)
val md_theme_dark_primaryContainer = Color(0xFF4f3d74)
val md_theme_dark_onPrimaryContainer = Color(0xFFebddff)
val md_theme_dark_secondary = Color(0xFFcdc2db)
val md_theme_dark_onSecondary = Color(0xFF342d40)
val md_theme_dark_secondaryContainer = Color(0xFF4b4358)
val md_theme_dark_onSecondaryContainer = Color(0xFFe9def8)
val md_theme_dark_tertiary = Color(0xFFf0b7c5)
val md_theme_dark_onTertiary = Color(0xFF4a2530)
val md_theme_dark_tertiaryContainer = Color(0xFF643b46)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9e1)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF151218)
val md_theme_dark_onBackground = Color(0xFFe7e0e8)
val md_theme_dark_surface = Color(0xFF151218)
val md_theme_dark_onSurface = Color(0xFFe7e0e8)
val md_theme_dark_surfaceVariant = Color(0xFF49454e)
val md_theme_dark_onSurfaceVariant = Color(0xFFcbc4cf)
val md_theme_dark_outline = Color(0xFF948f99)
val md_theme_dark_outlineVariant = Color(0xFF49454e)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFe7e0e8)
val md_theme_dark_inverseOnSurface = Color(0xFF322f35)
val md_theme_dark_inversePrimary = Color(0xFF68548e)